version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: myapp:latest
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/myapp
      - /usr/src/myapp/node_modules
    environment:
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - db
    command: npm run start:all

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      
  prisma:
    image: node:18-alpine
    volumes:
      - .:/usr/src/app  # 프로젝트 전체를 마운트
    working_dir: /usr/src/app  # 작업 디렉토리 설정
    environment:
      DATABASE_URL: ${DATABASE_URL}
    command: npx prisma studio  # Prisma Studio 실행
    ports:
      - "5555:5555"
    depends_on:
      - db

volumes:
  postgres_data: