version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: myapp:latest
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/myapp
      - /usr/src/myapp/node_modules
    environment:
      DATABASE_URL: ${DATABASE_URL}  # .env 파일에서 DATABASE_URL 읽기
    depends_on:
      - db
    command: npm run start:all

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}  # .env 파일에서 POSTGRES_USER 참조
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}  # .env 파일에서 POSTGRES_PASSWORD 참조
      POSTGRES_DB: ${POSTGRES_DB}  # .env 파일에서 POSTGRES_DB 참조
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: